### ISSUE TITLE
Unauthorized error

### ISSUE THREAD

**Issue by blobgamestudio** [burakoner/BtcTurk.Net#1]
It gives Unauthorized error, I set default options before create client. I checked my ip adress from btcTurk and permissions.Everything seems alright but it gives error. Did I forget something before get account balance ? 

`using BtcTurk.Net;
using CryptoExchange.Net.Authentication;

public class BtcTurkController
{
    private BtcTurkClient client;
    
    public void Initialize()
    {
        Authenticate();
        client = new BtcTurkClient();
        var ping = client.Ping();
        Debug.Log($"BtcTurk Ping: {ping.Success}");
    }

    private void Authenticate()
    {
        BtcTurkClient.SetDefaultOptions(new BtcTurkClientOptions()
        {
            ApiCredentials = new ApiCredentials(Constants.BtcTurkApiKey, Constants.BtcTurkApiSecret),
        });
    }
    
    public async void GetAccountInfo()
    {
        try
        {
            var accountInfo = await client.GetBalancesAsync();
            if (accountInfo.Success)
            {
                string text = $"BtcTurk account info: {accountInfo.Data.Length}";
                foreach (var balance in accountInfo.Data)
                {
                    if (balance.Balance > 0)
                    {
                        text += $"\n{balance.Asset} -> {balance.Balance}";
                    }
                }
                
                Debug.Log(text);
            }
            else
            {
                Debug.Log($"error {accountInfo.ResponseStatusCode}");
            }

        }
        catch
        {
            Debug.Log("An error occurred");
        }
    }
}`

**Comment by burakoner** [comment]
I am inspecting and will answer soon

**Comment by burakoner** [comment]
I fixed https://github.com/burakoner/BtcTurk.Net/blob/master/BtcTurk.Net/BtcTurkAuthenticationProvider.cs both in github and nuget. Unfortunatelly there is not documentation for v2.

**Comment by blobgamestudio** [comment]
Thank you so much. They are going to disable v1 but they haven't well documentation for v2. I tested and it works well. You saved my time thanks.

**Comment by burakoner** [comment]
I have only a swagger file for v2. I asked for authentication rules and they said there is no document for auth for v2

**Comment by blobgamestudio** [comment]
Is it possible to subscribe to models for example order book , balance updated etc (https://docs.btcturk.com/#models) from BtcTurkSocketClient.cs ? I could't find method for subscription other than subscribetoKlineStream.

**Comment by burakoner** [comment]
Not yet. I added to next version jobs

**Comment by blobgamestudio** [comment]
What is your release estimation date for next version ?

**Comment by burakoner** [comment]
Give me two days. I will write it for you

**Comment by blobgamestudio** [comment]
Thank you , I will wait your new release.

**Comment by burakoner** [comment]
I've just committed new version. https://github.com/burakoner/BtcTurk.Net/commit/fca382d54ce51c94aa5806c430c7d7a4c358a453

I added all WSS public endpoints but private ones. Because there isnt any documentation how to create login token. I've written to BtcTurk, If I get answer I can add private endpoints later.

You can clone my repo or download from nuget for the new version

**Comment by blobgamestudio** [comment]
Thank you so much , I tested. Looks good.
