### ISSUE TITLE
Websocket Ticker Last Price

### ISSUE THREAD

**Issue by emin-karadag** [burakoner/BtcTurk.Net#10]
Merhabalar,
Websocket üzerinden SubscribeToTickerAsync() fonksiyonu ile "ticker" kanalına abone oldum.
Normalde (https://api.btcturk.com/api/v2/ticker?pairSymbol=BTC_USDT) adresinden de görüleceği üzere **last** diye bir alan var. Fakat gelen websocket cevabında "last" alanı yok.
Websocket üzerinden lastPrice'ı anlık olarak dinlemek istiyorum.
Yardımcı olur musunuz?
Teşekkürler.

**Comment by burakoner** [comment]
Merhaba

Rest API'de last price olmasına rağmen maalesef BtcTurk'ün bahsettiğiniz kanalı LastPrice diye bir veri vermiyor. Bunun yerine Ask ve Bid veriyor. Bunu BtcTurk'ün kendi sitesindeki WS akışını izleyerek de görebilirsiniz. Size mutlaka lazım olan şey eğer son fiyat ise tavsiyem klines ya da trades e abone olmanız.
