### ISSUE TITLE
Versiyon 1.2.1 Hatası

### ISSUE THREAD

**Issue by emin-karadag** [burakoner/BtcTurk.Net#11]
Merhaba,
Az evvel versiyonumu 1.2.0'dan 1.2.1'e yükselttim.
Bu yükseltme ile birlikte BtcTürk borsa bilgilerini alamadığımı fark ettim
Versiyonu tekrar 1.2.0'a geri çektim ve çalıştı.
Versiyon güncellemesi başka yerleri de bozmuş mu emin değilim.
Kolay gelsin.

![Adsız](https://user-images.githubusercontent.com/7556164/98481613-7ef6fd80-220c-11eb-9c1e-a35c56bdf4fb.png)

**Comment by burakoner** [comment]
Bilgilendirme için teşekkür ederim. CryptoExchange versiyonu ile ilgili bir problem. Üzerinde çalışıyorum. Gerekirse versiyonu geriye alacağım

**Comment by burakoner** [comment]
1.2.2'de sorunu hallettim. Yeniden teşekkür ederim.
