### ISSUE TITLE
Minimum Emir Tutarı

### ISSUE THREAD

**Issue by emin-karadag** [burakoner/BtcTurk.Net#12]
Merhaba BtcTürk sitesinde minimum emir tutarları aşağıdaki gibi listelenmiştir.
Örneğin buna göre BTCUSDT için minimum 1USDT, ETHUSDT için ise minimum 5USDT'lik işlem açmak gerekiyor.

![Ekran Alıntısı](https://user-images.githubusercontent.com/7556164/98559508-c1294900-22b7-11eb-988f-cb83160b0f4b.png)

Ancak API'den gelen Exchange bilgilerinde bir eksiklik var. **Filters** içerisindeki **MinExchangeValue** değeri her zaman web sitesinde gösterilen değerin **0.09 altında**. 

Örneğin aşağıdaki BTCUSDT için MinExchangeValue değeri 0.9 gösteriliyor. Oysa websitesinde 1 olarak belirtilmiş. Aynı şekilde manuel işlem açılmak istendiğinde de en az 1 dolar işlem açılabiliyor. 

![Adsız](https://user-images.githubusercontent.com/7556164/98559936-43b20880-22b8-11eb-886f-8b54a67f6f8e.png)

Api'den ETHUSDT için ise MinExchangeValue => 4.91 olarak geliyor. Ancak normalde en az 5 dolarlık işlem açılabiliyor.
Bir kaç yerde TickSize üzerinden hesap yapılması gerekiyor yazılıyordu. 
Bu konuda bir fikriniz var mı? Aradaki 0.09'luk değer komisyon mu? Bunun tam hesaplaması için TickSize üzerinden mi yoksa başka şekilde mi bir hesap yapmak gerekiyor?

Teşekkürler.

**Comment by emin-karadag** [comment]
**Düzeltme:** Arada her zaman 0.09'luk fark var demiştim, o yanlış. Değişkenlik gösteriyor. Örneğin BTCTRY için minimum emir miktarı 10 TL iken MinEchangeValue 9.99 geliyor. Aradaki fark 0.01

**Comment by burakoner** [comment]
BtcTurk.Net kütüphanesinin hiçbir yerinde alınan veriler yorumlanmıyor sadece yazılımcı tarafından okunabilir hale getiriliyor. Exchange Info verileri https://api.btcturk.com/api/v2/server/exchangeInfo adresinden GET ile çekiliyor. Url'ye tıklayarak bakabilirsiniz. Bahsettiğiniz veriler BtcTurk'ten gelmekte.

**Comment by emin-karadag** [comment]
Evet haklısınız, BtcTürk bu şekilde gönderiyor.
Peki sizce bunu neden yapıyor olabilir?
Aynı veri setindeki diğer değerler kullanılarak gerçek minimum emir miktarı bulunabilir mi?

**Comment by burakoner** [comment]
Tahminden öte yorum yapamam.
Ya algoritmalar ile alınan veri üzerinden hesaplanıyor ya da api ile verilen bilgiler dışındaki bir data ile kontroller yapılıyor. Kontrollerin sunucuda yapıldığını varsayarsak bence ikinci ihtimal daha olası. Ama dediğim gibi tahminden öte gidemeyiz
