### ISSUE TITLE
Sıfıra bölünme hatası

### ISSUE THREAD

**Issue by yigitdemirbass** [burakoner/BtcTurk.Net#13]
![hata](https://user-images.githubusercontent.com/74449474/99143627-124a8b80-2670-11eb-9f3f-413a26052dfb.PNG)

Çok nadir de olsa bazen şu şekilde bir hata alıyorum, nedenini tam olarak bulamadım. Bir fikriniz var mı acaba ?

**Comment by burakoner** [comment]
Merhaba. Yazınızı şimdi tesadüfen gördüm. 
Gönderdiğiniz OnData methodunu kontrol ettiniz mi?
