### ISSUE TITLE
Dokumantasyon bilgileri

### ISSUE THREAD

**Issue by mGungorr** [burakoner/BtcTurk.Net#14]
Merhaba Burak abi hatırlarsınız beni, projemi bitirdim ve uzun süredir hataları, ufak tefek düzeltmeleri , stratejileri falan düzelttim geliştirdim. Gelişmiş ve yüzdesel olarak çok karlı bir sistem çıktı ortaya. Büyük yardımınız oldu bana, gelen ilk karları sizinle paylaşacağımı belirtmiştim. Sayfadaki Btc cüzdanının güncel ve size ait olup olmadığını sormak için yazıyorum. Ben, cevabınızı aldıktan sonra bunu kaldırabilirsiniz.

**Comment by burakoner** [comment]
Malum girhub'dan çok fazla mail geliyor. Issue bildiriminizi yeni gördüm. Evet adresler bana ait. Güzel sonuçlar almanıza çok sevindim. Başarınıza vesile olmak benim için yeterli. Bol kazançlar diliyorum.

**Comment by mGungorr** [comment]
Teşekkürler @burakoner , eth olarak yolladım. Issue açmışken bir de soru sorayım :) Amount bilgisi için kullanılan bir channel var, Order Book Full adında. Lambda expression kullanmışsınız sanırım. Ben alım satımı All Tickers içerisinde yaptırıyorum. Bazen All tickers ile Order book arasında 0.5 saniye fark oluyor. Order book içerisindeki fiyat bilgisi daha güncel olabiliyor. Ama sanırım lambda'dan dolayı orda sonsuz döngü var, şartlarıma uyduğu an 10larca kez emir yollamaya çalışıyor. Break falan da kullanamıyorum. All tickersda böyle bi sorun yok, saniyede 1 veri geliyor, emiri kontrol ediyor, uyuyorsa alımını satımını yapıyor break olup, sonraki saniyeyi bekliyor. Aynı mantığı Order book içerisine nasıl implement edebilirim ?

**Comment by burakoner** [comment]
Öncelikle teşekkür ederim. Web socket tarafındaki lambda fonksiyonları sonsuz bir döngü değil tek seferlik çağırılan method kullanıyor. Tekrar tekrar aynı koda girmesinin sebebi ise sürekli olarak bir veri akışının olması ve her veri alındığında o lambda methodunu yeniden çağırması. Bunu önlemek için mutlaka yoğurt yiyişine göre farklı yöntemler olabilir. Benim yaklaşıımım ya bir flag koyarım ve o bu emrin gönderilip gönderilmediğini kontrol eder ona göre emir göndermediysem gönderirim ya da lambda dışındaki bir methodu çağırırım. Bu senin kurguna göre olan cevabımdı. Ancak bence asıl mesele daha farklı. Hangi yöntemi kullanırsan kullan eğer çok emir gönderen bir algoritman varsa her seferinde bu gönderilen emirler lambda methodunun işlem süresinin uzamasına ve arkada bir kuyruk oluşmasına, bu da doğal olarak bir müddet sonra güncel değil eski veriyi sanki güncelmiş gibi okumana sebep olur. Zamanında bahsetmiştim diye hatırlıyorum ama yeri gelmişken tekrar etmek isterim. Bu yapı yerine websocketin görevi yalnızca ve yalnızca veriyi almak ve memory ye kaydetmek olmalı. Bunun dışında görevi olmamalı. VEritabanına kaydetme işini bile başka bir method yapmalı, emir gönderme işini ve takibini başka bir method yapmalı. Bunların eş zamanlı çalışması için de Multithread kullanmalısın. Biraz kavramsal bahsettim ama umarım faydalı olmuştur.

**Comment by mGungorr** [comment]
Rica ederim. Aslında ilk başta her şeyi websocketler içerisinde yapıyordum, verdiğiniz tavsiyelerden sonra methodlar ile yapmaya çalıştım, tabi bi kısmını yazdığım için geri dönemedim. Thread oluşturmak maliyetli geldi, o yüzden threadpoollar kullanıyorum tüm alım satım vs koşullarında. Ama alım satım kontrol kısımları çok uzun en az 7 bin satır koddan bahsediyorum. Flag koymak benimde aklıma gelmişti denedim de ama bazen aynı milisaniye içerisinde art arda veri gelince flag'i aşabiliyor. Her seferinde verilerin güncel olduğundan emin olmak için sıfırlıyorum ve işlemlerden önce 0 değilse kontrolu yapıp işlemlere sokuyorum. Diyelimki ilk lambda methodu çalıştı hemen ardından ikinci kez çalıştı. İkisi aynı anda girmiş gibi oluyo, ve diyelimki çağrılan ilk lambda alımını satışını vs yaptı ve sıfırladı coin fiyat, miktar bilgisini vs. Hemen ardından gelen ikinci lambda alım satım koşullarına girdiğinde veriler sıfırlandığı için dividing by zero gibi hatalar veriyor. Tabi bunu her alım satım koşulunda kontrol ettirebilirim ama 200 kusur içiçe if ile flag kontrolu yapmam gerekebilir ki yine işe yaramayabilir. İf'e girdikten sonra verileri sıfırlanıp emir yollamaya çalışır ve yine dividing by zero gibi hata... Yani websocket içerisinde atama ve if kontrolleri dışında hiç bi şey yok aslında, olanlarda threadpool ile çalışanlar. 

`                                if (flag == 1 && sw.ElapsedMilliseconds > 150)
                                {
                                flag = 0;
                                //buying selling algorithm
                                }
`
yani buna bi kaç kez girmesi beni sonsuz döngü olarak düşündürmüştü, ama inceleyince sizin söylediğiniz gibiymiş. Flagi hemen sıfırlamama rağmen nasıl giriyor iki tane falan hala çözüm bulamadım. Şuan thodex için de bot geliştiririyorum bitmek üzere. Aynı mantığı oluşturmuş olduğunuz diğer borsa clientlerine de implement etmeyi hedefliyorum. Çok güzel bi kaynak sağlamışsınız :)

**Comment by burakoner** [comment]
Faydalı bulmana sevindim. Yazdığın program senin paranı yönetiyor. Bu nedenle hata toleransın olmamalı. Onu kendi haline bırakıp 1-2 ay hiç bakmadığın gün olmuş demektir. Ayrıca Thodex için de kolaylıklar diliyorum.

**Comment by burakoner** [comment]
Thodex için https://github.com/burakoner/Thodex.Net adresini kontrol etmek isteyebilirsin

**Comment by mGungorr** [comment]
İnceledim de malum websocket hizmeti yok thodexin, çok fazla istek gönderiyorum ve 2.saniyede ip'den engel yiyorum. Aklıma her saniye proxy değiştirmek geldi, işe yarıyor ama bazen çalışmayan proxy vs olduğunda bağlantı kopuyor. Mantıklı bir çözüm bulamadım. Aklınıza gelen bir çözüm yolu var mı acaba ? @burakoner

**Comment by burakoner** [comment]
Thodex e yazdım ama WS dokumantasyonunu paylaşmıyorlar sanırım. Cevap alamadım. Ancak yine de bir fikir var aklımda. Public olan websocket peri çözebilirim. Bu da çok faydalı olacaktır. Birkaç güne ihtiyacım olacak

**Comment by mGungorr** [comment]
Ben de daha önce sordum bi kaç kez, böyle bi çalışmalarının olmadığını söylediler. Tabii ki zaman sizin, güzel haberlerinizi bekliyor olacağım. @burakoner

**Comment by burakoner** [comment]
Yeni versiyonu ekledim. Hem github hem nuget'e. Kontrol edebilirsin. Public kullanım düşünmediklerinden bazı alışılmadık tasarım paternleri var. Misal soket açıldığı an itibariyle state(ticker) update ine bağlanıyor. Eğer bunu almak istemiyorsan tüm pariteler için abone olup sonrasında aboneliği kaldırman gerekiyor. Kod örneği readme ve projede mevcut. Bu durum ilginç bir şekilde proje çakışmasına ve dolayısıyla query gönderememe, sadece abonelik gönderebilmeme neden oluyor. Bazen anlaşılmadık şekilde bazı komutlardan sonra bağlantıyı kapatıyor. Muhtemelen komut sıklığını aşıyor olabilirim. Dokümantasyon olmadığından sadece yorum yapabiliyorum. Private feed lere normal API key haricinde bir api key ile bağlanılıyor. Bunun algoritmasını istemiştim Thodex'ten asıl yanıt alamadığım buydu. Ama asıl amaç borsa verilerini anlık almaktı. Şu an tüm public yayınları alabiliyoruz. Kolay gelsin. Bir problem olursa diğer takip edenlerin de faydalanabilmesi adına Thodex.Net üzerinden issue açarsan memnun olurum. İyi geceler.
