### ISSUE TITLE
Binance.Net Çakışması

### ISSUE THREAD

**Issue by emin-karadag** [burakoner/BtcTurk.Net#15]
Merhabalar,
`BtcTurk.Net` versiyon 1.2.3 sürümünü yani en son sürümü kullanıyorum.
Uygulamam ayrıca Binance entegrasyonu için `Binance.Net` kütüphanesini indirdim. (Sürüm: 6.4.1)
Binance.Net kütüphanesini ekledikten sonra Constructor'da tanımladığım **BtcTurkSocketClient** hata vermeye başladı.
Hata mesajını aşağıda görüntüleyebilirsiniz. Binance.Net kütüphanesini kaldırınca düzgün çalışmaya devam ediyor.
Her iki kütüphane de `CryptoExchange.Net` kütüphanesini kullanıyor. Bilmiyorum belki sorun buradan kaynaklanıyor olabilir.

**Binance.Net URL Adresi:** https://github.com/JKorf/Binance.Net

![Ekran Alıntısı](https://user-images.githubusercontent.com/7556164/101979921-52525d80-3c72-11eb-9950-5689a924a814.png)

**Comment by burakoner** [comment]
CryptoExchange base methodunun yapısının değişmesinden kaynaklanıyormuş. https://github.com/burakoner/BtcTurk.Net/commit/49dca26502d9d14400c1c99bdb5a505739a2e52a commit'i ile düzelttim. bir de bonus olarak api dokümantasyonlarını ekledim. Nuget'i de güncelledim.

**Comment by emin-karadag** [comment]
Evet, düzelmiş. Teşekkür ederim.
