### ISSUE TITLE
GetTradeTransaction hatası

### ISSUE THREAD

**Issue by guleryuzu** [burakoner/BtcTurk.Net#20]
Merhabalar, 
GetTradeTransaction metodu imzalanarak yollanması gerekiyor fakat imzalanmadan yollanmış bu sebeple authantication hatası dönüyor bilginize.

**Comment by burakoner** [comment]
Başka methodlarda da sorun varmış. Uyarın için teşekkür ederim. https://github.com/burakoner/BtcTurk.Net/commit/22528b775f993848ba536836babab20ebd60d775 ile düzelttim.
