### ISSUE TITLE
Nuget Install Hatası

### ISSUE THREAD

**Issue by real1blue** [burakoner/BtcTurk.Net#21]
Merhaba;

Bir yeni başlayan sorusu sormak isterim. Kütüphaneyi yüklemek istediğimde 
Could not install package 'BtcTurk.Net 2.5.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.6.1', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.			0	
şeklinde bir hata alıyorum. Uygulama geliştirmek için VS 2015 kullanmaktayım hangi frame work ile kütüphaneyi kullanabilirim?

Teşekkürler.

**Comment by burakoner** [comment]
Aslında açıklama gayet net.
BtcTurk.Net netstandard 2.0 ve 2.1 paketlerinde yayınlandı bu da .net framework ile bir uyum sorunu olmaması gerektiğine işaret eder. Projenizde referansları karıştıran başka kütüphaneler vardır. Biraz detaylı inceleyip  gerekirse her birisini teker teker yüklmekte fayda var. Kolay gelsin
