### ISSUE TITLE
CryptoExchange.Net Hatası

### ISSUE THREAD

**Issue by emin-karadag** [burakoner/BtcTurk.Net#22]
Merhabalar,
**Binance.Net** (v8.0.8) ile **BtcTurk.Net** (v2.5.0) aynı projede kullandığımda BtcTurk.Net ekran görüntüsüne paylaştığım hatayı vermektedir.
Kolay gelsin.

![hata](https://user-images.githubusercontent.com/7556164/158242387-1ad16cc6-ee0a-49b4-b5cc-785bd3968d00.png)

**Comment by burakoner** [comment]
Sebebi CryptoExchange.Net'in farklı versiyonlarını kullanmamız. JKorf sürekli yeni versiyon çıkarıyor ve her defasında yapı değişiyor. Bir kaç gün içinde fırsat bulduğumda güncelleyeceğim.

**Comment by emin-karadag** [comment]
@burakoner tamamdır çok teşekkürler :)

**Comment by burakoner** [comment]
https://github.com/burakoner/BtcTurk.Net/commit/22528b775f993848ba536836babab20ebd60d775 ile düzeldi
