### ISSUE TITLE
getorderbook

### ISSUE THREAD

**Issue by emrecg** [burakoner/BtcTurk.Net#27]
getorderbook endpointi hata vermeye başladı

**Comment by burakoner** [comment]
Kullandığın kodu paylaşabilir misin?

**Comment by emrecg** [comment]
BtcTurkClient apiClient = new BtcTurkClient();
 apiClient.SetApiCredentials(api_key, api_secret);

var btc__ = apiClient.GetOrderBook(islem_cifti);


hata açıklaması :

| Error | BtcTurk Rest Api | [2] Deserialize JsonReaderException: Could not convert string to integer: SUCCESS. Path 'code', line 1, position 5241., Path: code, LineNumber: 1, LinePosition: 5241, data: [Data only available in Trace LogLevel]
: Deserialize JsonReaderException: Could not convert string to integer: SUCCESS. Path 'code', line 1, position 5241., Path: code, LineNumber: 1, LinePosition: 5241 [Data only available in Trace LogLevel]
Exception thrown: 'System.NullReferenceException' in ecgProTr.exe
An exception of type 'System.NullReferenceException' occurred in ecgProTr.exe but was not handled in user code
Object reference not set to an instance of an object.

**Comment by burakoner** [comment]
Aşağıdaki resimde görüldüğü üzere BtcTürk başarılı sonuçlarda hata kodunu `"SUCCESS"` - string - olarak döndürmeye karar vermiş keyfe keder. Bu sadece OrderBook değil tüm endpointleri etkileyebilecek bir durum. 
https://www.nuget.org/packages/BtcTurk.Net/2.6.1 nuget paketi ile gerekli düzenlemeyi yaptım test ettim çalışıyor. Değişen dosyalar için github'a ancak akşam commit ekleyebilirim.

Bildirim için teşekkürler.

![Screenshot_1](https://user-images.githubusercontent.com/21169085/190156306-548f4d63-804a-425a-97bb-afc6ababf808.png)

**Comment by emrecg** [comment]
rica ederim katkılarınızdan dolayı ben teşekkur ederim. İyi çalışmalar.

**Comment by emrecg** [comment]
cancel order endpointinde de bir sıkıntı var

**Comment by emrecg** [comment]
NO_ORDER_MATCHES_YOUR_REQUEST
