### ISSUE TITLE
cancel order hata

### ISSUE THREAD

**Issue by emrecg** [burakoner/BtcTurk.Net#28]
NO_ORDER_MATCHES_YOUR_REQUEST hatası alıyorum

**Comment by odurmus06** [comment]
> NO_ORDER_MATCHES_YOUR_REQUEST hatası alıyorum

çözdünüz mü hocam

**Comment by odurmus06** [comment]
> NO_ORDER_MATCHES_YOUR_REQUEST hatası alıyorum

            var apiKey = "";
            var apiSecret = "";
            var nonce = new DateTimeOffset(DateTime.UtcNow).ToUnixTimeMilliseconds();
            string message = apiKey + nonce;
            using (HMACSHA256 hmac = new HMACSHA256(Convert.FromBase64String(apiSecret)))
            {
                byte[] signatureBytes = hmac.ComputeHash(Encoding.UTF8.GetBytes(message));
                string X_Signature = Convert.ToBase64String(signatureBytes);

                HttpClient client = new HttpClient();

                client.DefaultRequestHeaders.Add("X-PCK", apiKey);
                client.DefaultRequestHeaders.Add("X-Stamp", nonce.ToString());
                client.DefaultRequestHeaders.Add("X-Signature", X_Signature);

                HttpResponseMessage response = await client.DeleteAsync("https://api.btcturk.com/api/v1/order?id=12015259708");

                string contentString = await response.Content.ReadAsStringAsync();
            }

yukarıdaki kod ile cancel order yapabilirsiniz hocam

**Comment by burakoner** [comment]
Version 2.6.2 ile çözülmüş olması lazım.
