### ISSUE TITLE
Currency Cekim ve Yatirim Islemlerinin Aktifligi Eklenmemis

### ISSUE THREAD

**Issue by ertan2002** [burakoner/BtcTurk.Net#30]
Tam olarak olayi cözemesem de dökümantasyonda, API call'da ekstra olarak asagidaki özellikler de geliyor ancak bunun sizin wrapper'da bir karsiligini göremedim.

{
    "currencySymbol":"Btc",
    "withdrawalDisabled":false, --> means Btc withdrawals are enabled
    "depositDisabled":false --> means Btc deposits are enabled
}

https://docs.btcturk.com/public-endpoints/exchange-info#2.-crypto-information

bu kisimlari nasil alabiliriz?

**Comment by burakoner** [comment]
Version 2.6.5 ile ekledim.
