### ISSUE TITLE
Precision Nasil Bulunur?

### ISSUE THREAD

**Issue by ertan2002** [burakoner/BtcTurk.Net#31]
bu metod cagrilacak alinan symbol'un filtresinde cesitli bilgiler aliniyor
```
var symbols = exchangeData.Data.Symbols;           
var exchangeData = await BtcTurkClientManager.BtcTurkClient.GetServerExchangeInfoAsync();
var btcTurkSymbols  = symbols.Where(f => f.Denominator == "USDT" && f.Status == BtcTurkSymbolStatus.Trading).ToList();                         
foreach (var btcturkSymbol in btcTurkSymbols)
{
   var tickSize = btcturkSymbol.Filters.First().TickSize;
}
```
![image](https://user-images.githubusercontent.com/1535195/227714563-8a46d38a-d75d-40f7-9ef7-9c3e5efdfe4a.png)

Sitede 0.00000001 minimum deger ile basliyor ve 0.00000002 0.00000003 seklinde arttirilabiliyor

Ancak API'den gelen sonuc 0.0000000000001 seklinde. 
Dogru minimum deger nasil bulunur ve tabi ki dogru precision? 

Binance'da lotsizefilter kullanarak stepsize alinarak hesaplama yapilabiliyor
su sekilde
             var stepSize = binanceSymbol.LotSizeFilter?.StepSize
            var quantity = Math.Floor(baseAmount / stepSize) * stepSize;

**Comment by burakoner** [comment]
Yanılmıyorsam DenominatorScale

**Comment by ertan2002** [comment]
Tesekkürler verdiginiz cevap üzerinden dogru cevabi buldum. NumeratorScale dogru cevabi veriyor. BTC icin mesela 8 cikti , bunu kullanarak hesaplayabilirim.
