### ISSUE TITLE
Subscription limit

### ISSUE THREAD

**Issue by mGungorr** [burakoner/BtcTurk.Net#32]
Merhaba @burakoner, beni hatırladığınızı düşünüyorum :), yıllar önce yazmış olduğum botu güncellemek için bazı adımlar atmaya karar verdim.

```
            foreach (var pair in pairs)
            {
                sock.SubscribeToOrderBookFull(pair, (data) =>
                {
                    if (data != null)
                    {
                    }
                });
            }
```

ile tüm pairlerin order booklarını takip etmeye çalışıyorum. Aynı zamanda `SubscribeToTickersAsync` 'e de bağlıyım. Pairs içerisinde 188 tane pair var. Yukarıdaki logic ile kullandığımda yaklaşık 5-10 adet paire bağlanıp diğerlerine ait herhangi bir sonuç göstermiyor.

`BtcTurkSocketClientOptions` içerisinde kullanılmayan //MaxSocketConnections = 50 gördüm. Acaba herhangi bir yerde limit var mı diye düşündüm, sorunun kaynağı hakkında bir yorumunuz var mı acaba ?

**Comment by burakoner** [comment]
Merhaba.
BtcTurk ilgili limitleri paylaşmadığı için denenmesi gerekn birkaç farklı durum var
- Aynı IP adresinden kaç farklı socket bağlantısı kurulabilir?
- İkinci bir socket bağlantısı için ne kadar beklemek gerekir?
- Bir socket bağlantısından kaç farklı subscription kurulabilir?
- İkinci bir subscription için ne kadar beklemek gerekir?

Bu soruları ancak deneyerek cevaplayabiliriz. Başlamak için doğru sorular bence bunlar.

**Comment by mGungorr** [comment]
Bu soruları BtcTurk tarafına sordum ancak yanıt alamadım.

Kendi demelerimde de en fazla 15-16 adet subscription oluşuyor, birden fazla connection oluşturmak vs işe yaramıyor maalesef.

Teşekkürler.
