### ISSUE TITLE
Commissions

### ISSUE THREAD

**Issue by mGungorr** [burakoner/BtcTurk.Net#33]
Merhaba,

Btcturk endpointleri kullanıma açmış değil ancak bazı endpointlere erişebiliyoruz, preflight olarak gönderiliyor. Onlardan birisi de komisyon endpointi.

`Account_Commissions_Endpoint = "account/commissions";`

curl ile token vs girdikten sonra veriyi çekebiliyorum ancak BtcTurk.net ile kullanamadım.

`	Error	{: No credentials provided for private endpoint }	CryptoExchange.Net.Objects.NoApiCredentialsError`

hatası veriyor.

```
    public WebCallResult<BtcTurkCommissions> GetCommissions(CancellationToken ct = default) => GetCommissionsAsync(ct).Result;

    public async Task<WebCallResult<BtcTurkCommissions>> GetCommissionsAsync(CancellationToken ct = default)
    {
        var result = await SingleApi.ExecuteAsync<BtcTurkApiResponse<BtcTurkCommissions>>(SingleApi.GetUri(Account_Commissions_Endpoint, PublicVersion), method: HttpMethod.Get, ct, signed: true).ConfigureAwait(false);
        if (!result.Success) return result.AsError<BtcTurkCommissions>(new BtcTurkApiError(result.Error.Code, result.Error.Message, result.Error.Data));
        if (result.Data.ErrorCode != "SUCCESS" && result.Data.ErrorCode.ToInt32Safe() > 0) return result.AsError<BtcTurkCommissions>(new BtcTurkApiError(result.Data.ErrorCode.ToInt32Safe(), result.Data.ErrorMessage, null));

        return result.As(result.Data.Data);
    }

```
```
namespace BtcTurk.Net.Objects.RestApi;

public class BtcTurkCommissions
{
    public List<Datum> data { get; set; }
}

public class Datum
{
    public string pairSymbolNormalized { get; set; }
    public string pairSymbol { get; set; }
    public string taker { get; set; }
    public string maker { get; set; }
}
```

incelediğimden anladığım kadarıyla signed parametresi, bunun için kullanılıyor ancak her seferinde yukarıdaki hatayı alıyorum. Gözden kaçırdığım başka ne var acaba, yardımcı olabilir misiniz ?

**Comment by burakoner** [comment]
Bu endpoint yalnızca Bearer Auth ile çalışıyor. Api kimliği ile çağrı yapıldığında 401 hatası döndürüyor. Sanıyorum bunu özellikle sadece web sitesi ve uygulamasından çağırılabilsin diye yapmışlar.

**Comment by mGungorr** [comment]
Dediğiniz gibi muhtemelen. Yardım ve bilgilendirme için teşekkür ederim. 
İyi Çalışmalar.
