### ISSUE TITLE
Possible to use websocket datas with Rest API ?

### ISSUE THREAD

**Issue by mGungorr** [burakoner/BtcTurk.Net#4]
There is no endpoints on websocket channel, can we use rest api endpoints according to websocket datas ? If its possible, can you show me example code ?

Btw Thanks for contributions, Best Regards...

**Comment by burakoner** [comment]
Websocket bahsettiğin şekilde kullanılmaz. Ancak verisinin tamamı zaten normal Rest Api de mevcut. Tam olarak hangi dataya nasıl ihtiyacin olduğundan bahsedersen belki örnek kod iletebilirim

**Comment by mGungorr** [comment]
Öğrenme amaçlı bot yazmak istiyorum ama request sayısından dolayı ip banı yemek istemiyorum , Bu yüzden websocket ile fiyatları alıp rest api ile order oluşturmak istiyorum.

Denemek için şöyle bir şey yaptım ama rest api kısmında hiç bi şey olmuyor.

```
               var pairs = new List<string> {
                "BTCTRY"
            };

            /* BtcTurkSocketClient Object */
            var sock = new BtcTurkSocketClient(new BtcTurkSocketClientOptions { LogVerbosity = CryptoExchange.Net.Logging.LogVerbosity.Debug });

            /* Public Socket Endpoints: */
            var subs = new List<UpdateSubscription>();

            BtcTurkClient apiClient = new BtcTurkClient();
            var btc00 = apiClient.GetServerVersion();
            var btc01 = apiClient.GetServerTime();
            //var btc02 = apiClient.GetServerMobileVersion();
            var btc03 = apiClient.GetServerExchangeInfo();
            var btc04 = apiClient.GetServerPing();
            var btc05 = apiClient.GetTicker("BTCTRY");
            var btc06 = apiClient.GetTradesV2("BTCTRY");
            var btc07 = apiClient.GetPriceGraphHistory("BTCTRY", Net.Objects.BtcTurkPeriod.OneHour);
            // Single Ticker
            /**/
            {
                var subscription = sock.SubscribeToTicker("BTCTRY", (ticker) =>
                {
                    if (ticker != null)
                    {
                        Console.WriteLine($"Channel: {ticker.Channel} Event:{ticker.Event} Type:{ticker.Type} >> " +
                        $"B:{ticker.Bid} A:{ticker.Ask} PS:{ticker.PairSymbol} NS:{ticker.NumeratorSymbol} DS:{ticker.DenominatorSymbol} " +
                        $"O:{ticker.Open} H:{ticker.High} L:{ticker.Low} LA:{ticker.Close} V:{ticker.Volume} " +
                        $"AV:{ticker.AveragePrice} D:{ticker.DailyChange} DP:{ticker.DailyChangePercent} PId:{ticker.PairId} Ord:{ticker.OrderNum} ");
                    }
                    if (ticker.Event == "BTCTRY" && ticker.Low<=90000)
                    {
                        Console.WriteLine("--rest api--");
                        Console.WriteLine($"{btc01}\n{btc03}\n{btc04}\n{btc05}\n{btc06}\n{btc07}");
                    }
                });
                subs.Add(subscription.Data);
            }
Console.ReadLine();
```

Channel: ticker Event:BTCTRY Type:402 >> B:82651 A:82689 PS:BTCTRY NS:BTC DS:TRY O:85500 H:87000 L:82000 LA:82651 V:1670,81005605 AV:85044,259541 D:-2811 DP:-3,33 PId:1 Ord:0
--rest api--
CryptoExchange.Net.Objects.WebCallResult`1[BtcTurk.Net.Objects.BtcTurkTime]
CryptoExchange.Net.Objects.WebCallResult`1[BtcTurk.Net.Objects.BtcTurkServerExchangeInfo]
CryptoExchange.Net.Objects.WebCallResult`1[BtcTurk.Net.Objects.BtcTurkServerPing]
CryptoExchange.Net.Objects.WebCallResult`1[BtcTurk.Net.Objects.BtcTurkTicker[]]
CryptoExchange.Net.Objects.WebCallResult`1[BtcTurk.Net.Objects.BtcTurkTrade[]]
CryptoExchange.Net.Objects.WebCallResult`1[BtcTurk.Net.Objects.BtcTurkKline[]]

Bu şekilde çıktı alıyorum, amacım belli şartlar oluştugunda alım yapması...

**Comment by burakoner** [comment]
Websocket ile emir gönderemezsin. Sorunun api limitleri ise kodlarda api rate limiters mevcut.

Aşağıdaki şekilde bir client seçenekleri belirleyebilirsin. 

```
var cliOptions = new BtcTurk.Net.BtcTurkClientOptions
            {
                // Rate Limiters
                RateLimiters = new List<CryptoExchange.Net.Interfaces.IRateLimiter>
                {
                    // 60 Saniyede 1000 Request
                    new CryptoExchange.Net.RateLimiter.RateLimiterTotal(600, TimeSpan.FromMilliseconds(60*1000)),

                    // 15 Saniyede 100 Request
                    new CryptoExchange.Net.RateLimiter.RateLimiterTotal(100, TimeSpan.FromSeconds(15)),
                },

                // Rate Limiting Behaviour
                RateLimitingBehaviour = CryptoExchange.Net.Objects.RateLimitingBehaviour.Wait,
            };
```

Birden fazla dilediğin şekilde rate limiter belirleyebilirsin. Bu seçenekleri aşağıdaki şekilde global tanımlayabilirsin.

`BtcTurk.Net.BtcTurkClient.SetDefaultOptions(cliOptions);`

veya sadece client nesnesine özel tanımlamak istersen `var cli = new BtcTurkClient(cliOptions);` gibi de kullanabilirsin.

Emir göndermek için aşağıdaki kodlar yeterli olacak.
```
            var cli = new BtcTurkClient();
            cli.SetApiCredentials("API-KEY", "API-SECRET");
            var order = cli.PlaceOrder("BTCTRY", 1.0m, Net.Objects.BtcTurkOrderSide.Buy, Net.Objects.BtcTurkOrderMethod.Market);
```

Umarım yardımcı olur. Senin için tek sorun algoritmanın neye göre çalışıp emirlerin ne zaman gönderileceğini belirlemek. Bu süreçte websocket verilerini kullanabilirsin daha doğru olur. algoritmadaki kurallar karşılandığı zaman normal rest api client ile emir iletebilirsin.

**Comment by mGungorr** [comment]
sock.SubscribeToOrderBookFull altındaki belirli bir coin için ask[1]'e, bid[1]'e ( ATOMTRY pairinin ilk satış emri mesela ), amount'a,  sock.SubscribeToTickers altında nasıl ulaşabilirim ?

SubscribeToTickers ile coinler için fiyat kontrolu vs yapıyorum ancak şartlarıma uyan X coininin en üstteki bid ve ask miktarı kadar alış satış yapmak istiyorum.
Bu arada botun yapacağı işlem sonuçları karlı gibi gözüküyor şimdilik :) İlk işlem karlarını sizinle paylaşmak isterim

**Comment by burakoner** [comment]
Sanıyorum aşağıdaki kod senin işini görür

`            // Variables
            var dictOrderBook = new Dictionary<string, BtcTurkStreamOrderBookFull>();
            var dictTickers = new Dictionary<string, BtcTurkStreamTickerRow>();

            // Objects
            var sock = new BtcTurkSocketClient();
            var cli = new BtcTurkClient();
            cli.SetApiCredentials("APIKEY", "APISECRET");

            // Order Book Full
            var pairs = new List<string> {
                "ATOMTRY","BTCTRY","DASHTRY","EOSTRY","ETHTRY","LINKTRY","LTCTRY","NEOTRY","USDTTRY","XLMTRY","XRPTRY","XTZTRY",
                "ATOMUSDT","BTCUSDT","DASHUSDT","EOSUSDT","ETHUSDT","LINKUSDT","LTCUSDT","NEOUSDT","XLMUSDT","XRPUSDT","XTZUSDT",
                "ATOMBTC","DASHBTC","EOSBTC","ETHBTC","LINKBTC","LTCBTC","NEOBTC","XLMBTC","XRPBTC","XTZBTC"
            };
            foreach (var pair in pairs)
            {
                sock.SubscribeToOrderBookFull(pair, (data) =>
                {
                    if (data != null)
                    {
                        dictOrderBook[pair] = data;
                    }
                });
            }

            // All Tickers
            sock.SubscribeToTickers((data) =>
            {
                if (data != null)
                {
                    foreach (var ticker in data.Items)
                    {
                        dictTickers[ticker.PairSymbol] = ticker;

                        Console.WriteLine($"Channel: {data.Channel} Event:{data.Event} Type:{data.Type} >> " +
                            $"B:{ticker.Bid} A:{ticker.Ask} PS:{ticker.PairSymbol} NS:{ticker.NumeratorSymbol} DS:{ticker.DenominatorSymbol} " +
                            $"O:{ticker.Open} H:{ticker.High} L:{ticker.Low} LA:{ticker.Close} V:{ticker.Volume} " +
                            $"AV:{ticker.AveragePrice} D:{ticker.DailyChange} DP:{ticker.DailyChangePercent} PId:{ticker.PairId} Ord:{ticker.OrderNum} ");

                        var algorithm = false;
                        // TODO: Trade Algorithm

                        if (algorithm)
                        {
                            if (dictOrderBook.ContainsKey(ticker.PairSymbol))
                            {
                                var order = cli.PlaceOrder(
                                    pairSymbol: ticker.PairSymbol,
                                    price: dictOrderBook[ticker.PairSymbol].Asks[0].Price,
                                    quantity: dictOrderBook[ticker.PairSymbol].Asks[0].Amount,
                                    orderSide: Net.Objects.BtcTurkOrderSide.Buy,
                                    orderMethod: Net.Objects.BtcTurkOrderMethod.Market
                                    );
                            }
                        }

                    }
                }
            });

            Console.ReadLine();`

Paratica'da her bir data farklı thread tarafından beslenir ve veriler tek noktaya toplanır. Her bir farklı thread üzerinde çalışan bot ilgili verileri alıp algooritmayı çalıştırır. Multithread senin olmazsa olmazın olacak. Bir diğer nokta hem `BtcTurkSocketClient` hem de `BtcTurkClient` `IDisposable` yapıdadır. yani `using` ile kullanabilirsin. Console uygulamalarında kod bloğu bitince using dışına çıktığı için client nesneleri yok olduğu için ben bu şekilde kullandım ancak senin using kullanmanı şiddetle tavsiye ederim.

**Comment by mGungorr** [comment]
Çok teşekkür ederim yardımların için Burak abi, Farklı bi yolla yapmıştım ama spagetti şeklindeydi, gönderdiğinize göre entegre ettim,teşekkürler. Henüz kullanılmıyor ama threadleri de oluşturdum, paratica mantığıyla her işlemi threadlere ayırmayı planlıyorum ancak suan kafamı iki şey kurcalıyor. 4 borsa arasında fiyat karşılaştırıp ona göre alıp ona göre satmayı planlıyorum, alacagım coinin indikatör kıyasını da başka yerden yapıyorum, borsaların fiyat farklarıyla da arbitraj özelliği entegre etmek istiyorum. ancak asıl alım btcturk'de olacagı için biraz daha hızlı çalışmasını istiyorum. Ne gibi bi tavsiyeniz olabilir ? Daha hızlı yapmak için ne yapabilirim ?

**Comment by burakoner** [comment]
Daha hızlı? Borsalar websocketlerden real-time olarak bahsediyorlar. Ne kadar doğru bilemem ancak daha hızlısı yalnızca borsa sunucuları ile aynı network içinde olmakla mümkün. Çoğu AWS kullanıyor hatta büyük kısmı AWS'de de hangi lokasyonda olduklarının bilgilerini dahi paylaşıyorlar. İnceleyebilirsin. Ancak kod olarak bu işlemler mikro ya da nanosaniyeler içinde gerçekleşiyor, kodlama ile daha hızlısı olmaz benim bilgimce.

Kolaylıklar diliyorum
