### ISSUE TITLE
Order Olusturma

### ISSUE THREAD

**Issue by codecreator00** [burakoner/BtcTurk.Net#5]
Selamlar, daha onceden kullandigim buy, sell order bir kaç saattir calismiyor. Btcturk icerisinde kullanici hareketlerinde de göremiyorum. Sizde sorunsuz calisiyor mu ? Sorunun kaynagi ne olabilir ?

**Comment by burakoner** [comment]
Eğer nuget paketini kullanıyorsanız değişiklik yapılmadı. Github reposunu kopyaladıysanız https://github.com/burakoner/BtcTurk.Net/commit/55d31cb57f0017e5dbcb6d6635f08c50bf9c1efb adresinde olduğu gibi bir isim hatası vardı biraz önce düzelttim. Eskiden indirdiniz hiç değişiklik yapmadığınız halde bugün çalışmıyorsa btcturk tarafında da bir sorun olabilir. Siz yaşadığını problemi daha teknik olarak anlatırsanız yardımcı olmaya çalışırım.

**Comment by codecreator00** [comment]
Evet nuget paketi. Sanırım btcturk tarafından kaynaklanıyor. Bi kaç kez bağlantı kopması olup tekrar bağlanmıştı. Ondan sonra   
                                
```
Console.WriteLine($"ALİNACAK MIKTAR: {low} DOLAR");
                                    var firstBuyOrder = cli.PlaceOrder("BTCUSDT", low, Net.Objects.BtcTurkOrderSide.Buy, Net.Objects.BtcTurkOrderMethod.Market);
```

şeklindeki hiç bir order oluşmadı. Kodda hata vermiyor gerçekleşmiyor sadece, sonradan farkettim ben de

**Comment by burakoner** [comment]
Ben test ettiğimde herhangi bir hata almadım. Konuyu kapatıyorum eğer yinelerse lütfen yeniden aç.

**Comment by codecreator00** [comment]
Tekrar selam, dün herhangi bi hata almıyordum ancak order da gerçekleşmiyordu. Az önce tekrar denedim şuan hata mesajı geliyor şu şekilde

**2020.08.09 12:35:43:621 | Debug | All subscription successfully resubscribed on reconnected socket.
0x2474 iş parçacığı 0 (0x0) koduyla çıktı.
0x2588 iş parçacığı 0 (0x0) koduyla çıktı.
2020.08.09 12:36:03:625 | Info | Socket 1 error: System.IO.IOException: Unable to read data from the transport connection: Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı..
 ---> System.Net.Sockets.SocketException (10054): Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı.
   --- End of inner exception stack trace ---
   at System.Net.Security.SslStream.<WriteSingleChunk>g__CompleteAsync|210_1[TWriteAdapter](ValueTask writeTask, Byte[] bufferToReturn)
   at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory`1 buffer)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.SendInternalAsync(PosList`1 items)
2020.08.09 12:36:03:627 | Info | Socket 1 Connection lost, will try to reconnect after 00:00:05
2020.08.09 12:36:03:630 | Info | Socket 1 error: System.Net.Sockets.SocketException (10057): Yuva bağlı olmadığından ve (bir veri birimi yuvasında bir sento çağrısı kullanırken) adres sağlanmadığından bir veri gönderme veya alma isteğine izin verilmedi.
2020.08.09 12:36:08:639 | Debug | Socket 1 resetting
2020.08.09 12:36:08:642 | Debug | Socket 1 connecting
2020.08.09 12:36:13:651 | Warning | Request timed out
2020.08.09 12:36:13:660 | Warning | Socket 1 message processing slow (72832ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2020.08.09 12:36:13:663 | Debug | Socket 1 received data: [100,{"type":100,"id":0,"ok":true,"message":"join|tradeview:ATOMTRY_1"}]
2020.08.09 12:36:13:665 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"DASHTRY_1","join":true}]
2020.08.09 12:36:13:667 | Debug | Socket 1 received data: [428,{"D":1596965700,"P":"ATOMTRY","R":1,"O":"34.8700000000","H":"34.8700000000","L":"34.8700000000","C":"34.8700000000","V":"0","channel":"tradeview","event":"ATOMTRY_1","type":428}]
2020.08.09 12:36:13:670 | Info | Socket 1 error: System.Exception: You must send data by websocket after websocket is opened!
2020.08.09 12:36:13:671 | Debug | Socket 1 received data: [100,{"type":100,"id":0,"ok":true,"message":"join|tradeview:BTCTRY_1"}]
2020.08.09 12:36:13:674 | Debug | Subscription completed
2020.08.09 12:36:13:676 | Debug | Socket 1 connection failed, state: Connecting
2020.08.09 12:36:13:676 | Debug | Socket 1 received data: [428,{"D":1596965700,"P":"BTCTRY","R":1,"O":"85577.0000000000","H":"85577.0000000000","L":"85577.0000000000","C":"85577.0000000000","V":"0","channel":"tradeview","event":"BTCTRY_1","type":428}]
2020.08.09 12:36:13:682 | Debug | Socket 1 failed to reconnect
2020.08.09 12:36:18:688 | Debug | Socket 1 resetting
2020.08.09 12:36:18:691 | Debug | Socket 1 connecting
0x2718 iş parçacığı 0 (0x0) koduyla çıktı.
2020.08.09 12:36:23:680 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"EOSTRY_1","join":true}]
2020.08.09 12:36:23:682 | Info | Socket 1 error: System.Exception: You must send data by websocket after websocket is opened!
2020.08.09 12:36:23:684 | Debug | Socket 1 connection failed, state: Connecting
2020.08.09 12:36:23:687 | Debug | Socket 1 failed to reconnect
0x1538 iş parçacığı 0 (0x0) koduyla çıktı.
2020.08.09 12:36:28:699 | Debug | Socket 1 resetting
2020.08.09 12:36:28:701 | Debug | Socket 1 connecting
2020.08.09 12:36:33:692 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"ETHTRY_1","join":true}]
2020.08.09 12:36:33:695 | Info | Socket 1 error: System.Exception: You must send data by websocket after websocket is opened!
2020.08.09 12:36:33:697 | Debug | Socket 1 connection failed, state: Connecting
2020.08.09 12:36:33:699 | Debug | Socket 1 failed to reconnect
2020.08.09 12:36:36:602 | Debug | Socket 1 received data: [991,{"type":991,"current":"5.1.0","min":"2.3.0"}]
2020.08.09 12:36:38:712 | Debug | Socket 1 resetting
2020.08.09 12:36:38:716 | Debug | Socket 1 connecting
2020.08.09 12:36:39:042 | Debug | Socket 1 connected
2020.08.09 12:36:39:043 | Debug | Socket 1 received data: [991,{"type":991,"current":"5.1.0","min":"2.3.0"}]
2020.08.09 12:36:39:045 | Info | Socket 1 reconnected after 00:00:35.4179164
2020.08.09 12:36:39:049 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"ticker","event":"BTCTRY","join":true}]
2020.08.09 12:36:39:052 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"ticker","event":"all","join":true}]
2020.08.09 12:36:39:055 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"ATOMTRY_1","join":true}]
2020.08.09 12:36:39:058 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"BTCTRY_1","join":true}]
2020.08.09 12:36:39:061 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"DASHTRY_1","join":true}]
2020.08.09 12:36:39:063 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"ETHTRY_1","join":true}]
2020.08.09 12:36:39:125 | Debug | Socket 1 received data: [100,{"type":100,"id":0,"ok":true,"message":"join|ticker:BTCTRY"}]
2020.08.09 12:36:39:128 | Debug | Subscription completed
2020.08.09 12:36:39:131 | Debug | Socket 1 received data: [402,{"B":"85600","A":"85659","PS":"BTCTRY","H":"86249","L":"85025","LA":"85600","O":"85499","V":"708.51982259","AV":"85749.813858","D":"160","DP":"0.12","DS":"TRY","NS":"BTC","PId":1,"channel":"ticker","event":"BTCTRY","type":402}]
2020.08.09 12:36:39:156 | Debug | Socket 1 received data: [100,{"type":100,"id":0,"ok":true,"message":"join|ticker:all"}]
2020.08.09 12:36:39:159 | Debug | Subscription completed
2020.08.09 12:36:39:206 | Debug | Socket 1 received data: [401,{"items":[{"B":"85600","A":"85659","PS":"BTCTRY","H":"86249","L":"85025","DP":"0.12","LA":"85600","O":"85499","V":"708.51982259","AV":"85749.813858","D":"160","DS":"TRY","NS":"BTC","PId":1,"Ord":0},**
