### ISSUE TITLE
Order

### ISSUE THREAD

**Issue by codecreator00** [burakoner/BtcTurk.Net#6]
Selamlar @burakoner, pazar günü sizi rahatsız ediyorum ama k.bakmayın , sanırım issue'yi kapattığımız için son yazdıgım size bildirim olarak gelmedi ben hala order problemi yaşıyorum ve şöyle bi hata mesajı alıyorum, önceki mesajımı yapıştırıyorum buraya...

Tekrar selam, dün herhangi bi hata almıyordum ancak order da gerçekleşmiyordu. Az önce tekrar denedim şuan hata mesajı geliyor şu şekilde

**2020.08.09 12:35:43:621 | Debug | All subscription successfully resubscribed on reconnected socket.
0x2474 iş parçacığı 0 (0x0) koduyla çıktı.
0x2588 iş parçacığı 0 (0x0) koduyla çıktı.
2020.08.09 12:36:03:625 | Info | Socket 1 error: System.IO.IOException: Unable to read data from the transport connection: Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı..
---> System.Net.Sockets.SocketException (10054): Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı.
--- End of inner exception stack trace ---
at System.Net.Security.SslStream.g__CompleteAsync|210_1[TWriteAdapter](ValueTask writeTask, Byte[] bufferToReturn)
at System.Net.Security.SslStream.WriteAsyncInternal[TWriteAdapter](TWriteAdapter writeAdapter, ReadOnlyMemory1 buffer) at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.SendInternalAsync(PosList1 items)
2020.08.09 12:36:03:627 | Info | Socket 1 Connection lost, will try to reconnect after 00:00:05
2020.08.09 12:36:03:630 | Info | Socket 1 error: System.Net.Sockets.SocketException (10057): Yuva bağlı olmadığından ve (bir veri birimi yuvasında bir sento çağrısı kullanırken) adres sağlanmadığından bir veri gönderme veya alma isteğine izin verilmedi.
2020.08.09 12:36:08:639 | Debug | Socket 1 resetting
2020.08.09 12:36:08:642 | Debug | Socket 1 connecting
2020.08.09 12:36:13:651 | Warning | Request timed out
2020.08.09 12:36:13:660 | Warning | Socket 1 message processing slow (72832ms), consider offloading data handling to another thread. Data from this socket may arrive late or not at all if message processing is continuously slow.
2020.08.09 12:36:13:663 | Debug | Socket 1 received data: [100,{"type":100,"id":0,"ok":true,"message":"join|tradeview:ATOMTRY_1"}]
2020.08.09 12:36:13:665 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"DASHTRY_1","join":true}]
2020.08.09 12:36:13:667 | Debug | Socket 1 received data: [428,{"D":1596965700,"P":"ATOMTRY","R":1,"O":"34.8700000000","H":"34.8700000000","L":"34.8700000000","C":"34.8700000000","V":"0","channel":"tradeview","event":"ATOMTRY_1","type":428}]
2020.08.09 12:36:13:670 | Info | Socket 1 error: System.Exception: You must send data by websocket after websocket is opened!
2020.08.09 12:36:13:671 | Debug | Socket 1 received data: [100,{"type":100,"id":0,"ok":true,"message":"join|tradeview:BTCTRY_1"}]
2020.08.09 12:36:13:674 | Debug | Subscription completed
2020.08.09 12:36:13:676 | Debug | Socket 1 connection failed, state: Connecting
2020.08.09 12:36:13:676 | Debug | Socket 1 received data: [428,{"D":1596965700,"P":"BTCTRY","R":1,"O":"85577.0000000000","H":"85577.0000000000","L":"85577.0000000000","C":"85577.0000000000","V":"0","channel":"tradeview","event":"BTCTRY_1","type":428}]
2020.08.09 12:36:13:682 | Debug | Socket 1 failed to reconnect
2020.08.09 12:36:18:688 | Debug | Socket 1 resetting
2020.08.09 12:36:18:691 | Debug | Socket 1 connecting
0x2718 iş parçacığı 0 (0x0) koduyla çıktı.
2020.08.09 12:36:23:680 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"EOSTRY_1","join":true}]
2020.08.09 12:36:23:682 | Info | Socket 1 error: System.Exception: You must send data by websocket after websocket is opened!
2020.08.09 12:36:23:684 | Debug | Socket 1 connection failed, state: Connecting
2020.08.09 12:36:23:687 | Debug | Socket 1 failed to reconnect
0x1538 iş parçacığı 0 (0x0) koduyla çıktı.
2020.08.09 12:36:28:699 | Debug | Socket 1 resetting
2020.08.09 12:36:28:701 | Debug | Socket 1 connecting
2020.08.09 12:36:33:692 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"ETHTRY_1","join":true}]
2020.08.09 12:36:33:695 | Info | Socket 1 error: System.Exception: You must send data by websocket after websocket is opened!
2020.08.09 12:36:33:697 | Debug | Socket 1 connection failed, state: Connecting
2020.08.09 12:36:33:699 | Debug | Socket 1 failed to reconnect
2020.08.09 12:36:36:602 | Debug | Socket 1 received data: [991,{"type":991,"current":"5.1.0","min":"2.3.0"}]
2020.08.09 12:36:38:712 | Debug | Socket 1 resetting
2020.08.09 12:36:38:716 | Debug | Socket 1 connecting
2020.08.09 12:36:39:042 | Debug | Socket 1 connected
2020.08.09 12:36:39:043 | Debug | Socket 1 received data: [991,{"type":991,"current":"5.1.0","min":"2.3.0"}]
2020.08.09 12:36:39:045 | Info | Socket 1 reconnected after 00:00:35.4179164
2020.08.09 12:36:39:049 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"ticker","event":"BTCTRY","join":true}]
2020.08.09 12:36:39:052 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"ticker","event":"all","join":true}]
2020.08.09 12:36:39:055 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"ATOMTRY_1","join":true}]
2020.08.09 12:36:39:058 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"BTCTRY_1","join":true}]
2020.08.09 12:36:39:061 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"DASHTRY_1","join":true}]
2020.08.09 12:36:39:063 | Debug | Socket 1 sending data: [151,{"type":151,"channel":"tradeview","event":"ETHTRY_1","join":true}]
2020.08.09 12:36:39:125 | Debug | Socket 1 received data: [100,{"type":100,"id":0,"ok":true,"message":"join|ticker:BTCTRY"}]
2020.08.09 12:36:39:128 | Debug | Subscription completed
2020.08.09 12:36:39:131 | Debug | Socket 1 received data: [402,{"B":"85600","A":"85659","PS":"BTCTRY","H":"86249","L":"85025","LA":"85600","O":"85499","V":"708.51982259","AV":"85749.813858","D":"160","DP":"0.12","DS":"TRY","NS":"BTC","PId":1,"channel":"ticker","event":"BTCTRY","type":402}]
2020.08.09 12:36:39:156 | Debug | Socket 1 received data: [100,{"type":100,"id":0,"ok":true,"message":"join|ticker:all"}]
2020.08.09 12:36:39:159 | Debug | Subscription completed
2020.08.09 12:36:39:206 | Debug | Socket 1 received data: [401,{"items":[{"B":"85600","A":"85659","PS":"BTCTRY","H":"86249","L":"85025","DP":"0.12","LA":"85600","O":"85499","V":"708.51982259","AV":"85749.813858","D":"160","DS":"TRY","NS":"BTC","PId":1,"Ord":0},**

**Comment by burakoner** [comment]
Hatanız bu mu? ---> System.Net.Sockets.SocketException (10054): Varolan bir bağlantı uzaktaki bir ana bilgisayar tarafından zorla kapatıldı.

Bu Rest değil websocket api hatası. Order'la bağlantısını kuramadım. Order gönderdiğiniz kodu ve aldığınız çıktıyı iletir misiniz?

**Comment by Ogrenciyim** [comment]
o kısım sığmamış, "Server error: 1037, Unauthorized - Invalid Nonce" , {Date: Sun, 09 Aug 2020 19:37:22 GMT
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: __cfduid=dca3d796b77c13a289c45786e77cee1671597001842; expires=Tue, 08-Sep-20 19:37:22 GMT; path=/; domain=.btcturk.com; HttpOnly; SameSite=Lax, __cfruid=3d892798cdd9ed6f4630c7dcf9f8658a073e48da-1597001842; path=/; domain=.btcturk.com; HttpOnly; Secure; SameSite=None
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Vary: Origin, Access-Control-Request-Method, Access-Control-Request-Headers
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: X-Content-Type-Options, X-Frame-Options, X-XSS-Protection, Date, Transfer-Encoding, Vary
X-Content-Type-Options: nosniff
X-Frame-Options: DENY
x-xss-protection: 1; mode=block
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
cf-client-ip: 81.215.173.26
api-supported-versions: 1.0, 2.0
CF-Cache-Status: DYNAMIC
cf-request-id: 04765356a60000cb6211ae0200000001
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Server: cloudflare
CF-RAY: 5c03ee6aa8b4cb62-IST
}

**Comment by codecreator00** [comment]
Tarih/Saat eşitleyince düzeldi... Teşekkürler
