### ISSUE TITLE
Socket datas second by second

### ISSUE THREAD

**Issue by jeandelafontain** [burakoner/BtcTurk.Net#7]
Hey, I was searching exchanges and their api clients. I found yours but Why we are receiving datas second by second not realtime ?
How to get datas realtime, this looks like sending request in every second.

**Comment by burakoner** [comment]
No. Websocket is realtime. Why do you think like that?

**Comment by jeandalefontain** [comment]
```

            {
                var subscription = sock.SubscribeToTickers((data) =>
    {
        if (data != null)
        {
            foreach (var ticker in data.Items)
            {            }

            string timestamp = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff", CultureInfo.InvariantCulture);
            Console.WriteLine($"                                                                                                {timestamp}");
        }

    });
                subs.Add(subscription.Data);
            }
```

**Output like this**


![Capture00](https://user-images.githubusercontent.com/69894326/90610723-5e16a180-e1f5-11ea-9164-f44de2103afe.PNG)

**Comment by burakoner** [comment]
I understand you. This is BTCTurk algorithm. They dont stream live. They stream data with a timer unfortunatelly

**Comment by jeandealfontain** [comment]
Yeah not about you, you did good. Then I should check with requests, api docs says 600 per minute, thats x10 if we compare x|
How I can print ticker with api or get balances or cancel order ?
Returning like this **`CryptoExchange.Net.Objects.WebCallResult1[BtcTurk.Net.Objects.BtcTurkTicker[]]`**

Sorry for effortless question, Not working on .Net normally x|
After that you can close issue and accept my thanks x)

**Comment by jeandealfontain** [comment]
I have used even **reflection** and **typedescriptor** but couldnt find btc11 or others value. I know its embarrassing but If its easy for you can you show me , if its not thanks for everything. I found different apis but they are deprecated, yours up to date.

**Comment by burakoner** [comment]
There is an example below
```

            /* BtcTurkClient Object */
            BtcTurkClient apiClient = new BtcTurkClient();

            // Public Api Endpoints:
            var btc00 = apiClient.GetServerVersion();
            var btc01 = apiClient.GetServerTime();
            var btc03 = apiClient.GetServerExchangeInfo();
            var btc04 = apiClient.GetServerPing();
            var btc05 = apiClient.GetTicker("BTCTRY");
            var btc06 = apiClient.GetTradesV2("BTCTRY");
            var btc07 = apiClient.GetPriceGraphHistory("BTCTRY", Net.Objects.BtcTurkPeriod.OneHour);

            // Private Api Endpoints:
            apiClient.SetApiCredentials("xxxxx", "xxxxx");
            var btc11 = apiClient.GetBalances();

            if (btc11.Success)
            {
                    Console.WriteLine("Balances");
                foreach (var balance in btc11.Data)
                {
                    Console.WriteLine($"Asset:{balance.Asset} Name:{balance.AssetName} Balance:{balance.Balance} Free:{balance.Free}");
                }
            }


```
If you want to see object structure, you need to set a breakpoint and start debug, you will see all variables in Locals window.

![Screenshot_2](https://user-images.githubusercontent.com/21169085/91183966-c3d2c400-e6f4-11ea-954c-197577cf7b83.png)

**Comment by jeandealfontain** [comment]
Wow, studio is a great tool. It may best thing on VS that i have ever seen (btw im prettty new x) )
Thanks for code and actually that info, That's what i need it.

**Comment by burakoner** [comment]
I'm happy that the code worked for you. I'm closing the issue. Have a nice day
