### ISSUE TITLE
BtcTürk WebSocket Sipariş Dinleme

### ISSUE THREAD

**Issue by emin-karadag** [burakoner/BtcTurk.Net#9]
Merhabalar,
BtcTürk ekibi ile yaptığım görüşmeler sonucunda Websocket üzerinden sipariş takibi yapılabildiğini söylediler.
Şöyle ki: Mevcut bir sipariş açıldığında/kapandığında/iptal edildiğinde soket üzerinden bunun bilgisi veriliyormuş.

Websocket bağlantısı yaparken 111 kodlu mesajı göndermek gerektiğini söylediler, oturum açılabilmesi için.

Sorum şu: Şu anda BtcTurk.Net C# kütüphanenizde Websocket üzerinden sipariş dinlemesi yapılabiliyor mu? Eğer yapılabiliyorsa, soket üzerinden nasıl oturum açıldığı ile ilgili örnek bir kod bloğu paylaşabilir misiniz? 
Eğer sipariş dinlemesi yapılamıyorsa şu anda, yakın zamanda bu özelliği eklemeyi düşünüyor musunuz?
Teşekkürler. :)

**Comment by burakoner** [comment]
BTCTurk websocket üzerinden nasıl oturum açılabileceğinin dokümantasyonunu paylaşmıyor. Bu nedenle websocket tarafında oturum açılmadan alınan veriler mevcut. Eğer OTP kodu olarak size 111 girmenizi söyledilerse bu ciddi bir açıktır nerede kaldı OTP?

**Comment by emin-karadag** [comment]
BtcTürk Websocket için benim açtığım Issue'yi aşağıda paylaşıyorum. Burada açıkça 111 kodu ile gönderim yaparak Login olunabilir deniliyor.
https://github.com/BTCTrader/broker-api-docs/issues/270

Ayrıca gene Websocket üzerinden Login olma ile ilgili diğer bir kaç arkadaşın açtığın Isuue'lar da faydalı olabilir:
https://github.com/BTCTrader/broker-api-docs/issues/276
https://github.com/BTCTrader/broker-api-docs/issues/274

Sanırım bir Token vasıtasıyla 111 kodlu mesaj üzerinden websocket oturum açma işlemi yapılabiliyor. Kütüphanenize bu özelliği eklerseniz çok faydasını göreceğiz :)

**Comment by burakoner** [comment]
İlerleyen versiyonlarda daha detaylı inceleyebilirim. Hatırladığım kadarıyla başka sıkıntılar da vardı çünkü.

**Comment by emin-karadag** [comment]
Tamamdır, teşekkür ederim. Dört gözle bekliyorum :)
